<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check Accidents</name>
  <uuid>9c6449f3-5be3-4983-b8e4-e5d95f41809f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each driver, in the drivers of request 
definitions
    set 'name' to the first name of this driver ;
if
    the number of accidents of this driver is less than 0
then
    add "The number of accidents for " + name + " cannot be less than 0" to decision ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
