<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check Min, Max Age</name>
  <uuid>0c192d89-5d9a-45be-81a8-b9e6ffd6b4a2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each driver, in the drivers of request 
definitions
    set 'name' to the first name of this driver ;
if
    any of the following conditions is true :
            - the age of this driver is less than 16 
            - the age of this driver is more than 100 ,then
    add "The driver's age (" + name + ") is beyond the coverage range" to decision ;


]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
