<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check Coverage Request</name>
  <uuid>ab2fe261-de49-4769-a92c-8968a8f029e3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    there is no vehicle coverage request in the vehicle coverages of request 
then
    add "There is no vehicle coverage request in the Auto quote request" to decision ;


]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
