<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check Age</name>
  <uuid>6014be4b-d701-45ab-84eb-2cbd0145b201</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each driver, in the drivers of request 
definitions
    set 'name' to the first name of this driver ;
if
    the age of this driver is less than 0
then
    add "The age for driver, " + name + ", cannot be less than 0" to decision ;


]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
