<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>dcd4fa44-5d02-4cc0-bf00-bc126245e015</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of strings ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
