<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ca461b03-d7ae-4bbb-9ac1-de6baf59149c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new eligibility response where
        eligible is true, 
        the main message is "" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
