<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Too Young</name>
  <uuid>85191c34-8ab5-4cc0-8057-da06a0b90542</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each driver, in the drivers of 'validated request' 
definitions
    set 'name' to the first name of this driver ;
if
    the age of this driver is less than 18 
then
set decision to a new eligibility response where
        eligible is false, 
        the main message is "Intellinsure does not assure individuals who are younger than the required age (" + name + ")" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
