<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>compute price</name>
  <uuid>a31e5025-bf9d-4136-88a8-ec774657953d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each vehicle quote item, in 'vehicle quote items' 
  add the total vehicle price of this vehicle quote item to decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
