<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>e349c7df-8608-4715-b55b-b87e649901b5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new line item where
        the message is "no surcharge has been applied", 
        the value is 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
