<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Anti-lock Brakes Discount</name>
  <uuid>dfa46d9a-ff73-410f-98a0-334890f3e009</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
   the coverage type of 'coverage request' is collision and 
    'state of residence' is not "NJ" and
   the vehicle of 'vehicle coverage request' is anti lock brakes
then
    add a new line item where 
       the value is (2 * the value of 'base premium') / 100,
       the message is "Anti-lock Brakes Discount" 
    to decision;


]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
