<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>e5d41898-592d-4ed7-bc18-447fd482bb8b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of line items ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
