<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Pickup Truck Discount</name>
  <uuid>80f3adfd-91c1-4f4a-a903-33736a964466</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
   the coverage type of 'coverage request' is collision and 
   the vehicle type of the vehicle of 'vehicle coverage request' is pickup 
then
    add a new line item where 
       the value is (2 * the value of 'base premium') / 100,
       the message is "Pickup Truck Discount"
    to decision;


]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
