<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>copy input</name>
  <uuid>6acc84e7-f026-4b48-b706-81d81e5b6548</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'eligibility result' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
