<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Too Many Accidents</name>
  <uuid>42f4394e-53a8-441e-bc7a-1da18e71e876</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each driver, in the drivers of 'validated request' 
definitions
    set 'name' to the first name of this driver ;
if   the number of accidents of this driver is more than 2
then
    add "The driver (" + name + ") has been involved in too many accidents" to decision;

]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
