<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>compute quotes</name>
  <uuid>40314243-d037-4195-bb20-cf5fd862c4eb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each coverage item , in the coverages of 'vehicle coverage request' 
  add  the coverage quote computed from 
    coverage request being this coverage item , 
    state of residence being 'state of residence' , 
    vehicle coverage request being 'vehicle coverage request' ,
    auto quote request being 'auto quote request' ,
    today being today
  to decision ;




]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
