<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Collision - Sports Coupe Surcharge</name>
  <uuid>5e3dbe78-b220-4070-b01a-1dc4b0163bfe</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the coverage type of 'coverage request' is collision and
    the vehicle type of the vehicle of 'vehicle coverage request' is sports coupé  
then
    add a new line item where
        the message is "Sports Coupe Surcharge", 
        the value is (4 * the value of 'base premium') / 100 
   to decision ;



]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
