<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Comprehensive - SUV Surcharge for NJ</name>
  <uuid>8532bc1e-133f-4aeb-aba5-92107e0aac4d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the coverage type of 'coverage request' is comprehensive and
    'state of residence' is "NJ" and
    the vehicle type of the vehicle of 'vehicle coverage request' is SUV  
then
    add a new line item where
        the message is "NJ Sports Utility Vehicle surcharge", 
        the value is (1.5 * the value of 'base premium') / 100 
   to decision ;





]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
