<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Comprehensive - Sedan Surcharge</name>
  <uuid>ed470379-a10f-45ff-85bd-5987948fcd0c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the coverage type of 'coverage request' is comprehensive and
    the vehicle type of the vehicle of 'vehicle coverage request' is sedan  
then
    add a new line item where
        the message is "Sedan surcharge", 
        the value is 10 
   to decision ;





]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
