<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Mechanical Breakdown - Old Vehicle Surcharge</name>
  <uuid>285e3f2f-d7d9-48a4-bc88-9aa71bfc3964</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the coverage type of 'coverage request' is mechanical breakdown and
    the year of the registration date of the vehicle of 'vehicle coverage request' is before the year 1996 
then
    add a new line item where
        the message is "Old Vehicle Surcharge", 
        the value is 3.5 
   to decision ;





]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
