<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>86ef706a-6b53-4d9f-b774-27bfa43bad35</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of line items ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
