<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>select drivers</name>
  <uuid>6f54d24c-2c0a-42de-a8a7-48b719358728</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each driver, in the drivers of 'auto quote request' 
if the maximum percentage usage of all vehicle usages in the usages of 'vehicle coverage request' ,
      where the driver id of each vehicle usage is the driver id of this driver,
   is at least 50
then
add this driver to decision ;


]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
