<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0d961164-25bd-4e2c-92f7-3a6fa62cc9a1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new line item where
        the message is "no discount has been applied", 
        the value is 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
