<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>select driver</name>
  <uuid>302890bd-d595-47de-957a-f4b72fbd76d2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each driver, in the drivers of 'auto quote request' 
if the maximum percentage usage of all vehicle usages in the usages of 'vehicle coverage request' ,
      where the driver id of each vehicle usage is the driver id of this driver,
   is at least 50
then add this driver to decision;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
