<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>compute quotes</name>
  <uuid>4278fe36-5bf4-4212-83e7-8c57ba1695bd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each vehicle coverage request ,  in the vehicle coverages of request 
  add the vehicle coverage quote computed from  
    vehicle coverage request being this vehicle coverage request,
    auto quote request being request ,
    state of residence being 'state of residence',
    today being today
  to decision ;

 








]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
